# Generated by Django 4.2 on 2023-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_writer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bookImage')),
            ],
        ),
    ]
